#!/usr/bin/env python3
"""Build a read-only copy of the site for GitHub Pages.

    .venv/bin/python export_static.py

The hosted build has no server behind it, so it is read-only by construction:
no journal, no source list, no run history. Those panels are *removed from the
markup* rather than hidden, because a display:none add-a-handle form is still a
working form to anyone who opens devtools.

**Journal notes are never exported.** They live inside news/*.md, and this is
what makes publishing safe: the export renders only the news body, which
digest.render_html already cuts at the notes heading. news/ itself is
git-ignored, so the raw markdown never leaves the machine.

Parsing and rendering go through digest.py, the same code the live server uses,
so the two views cannot drift apart.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

from src import atomic, digest

MARKER = ".daily-news-export"
NOJEKYLL = ".nojekyll"

ASSETS = ("index.html", "style.css", "app.js", "header.PNG")

# `<details ... data-live-only ...>...</details>`, including nested markup.
_LIVE_ONLY = re.compile(
    r"[ \t]*<(?P<tag>\w+)\b[^>]*\bdata-live-only\b.*?</\1>\s*",
    re.DOTALL | re.IGNORECASE,
)


class UnsafeTarget(Exception):
    """The output directory holds something this tool did not put there."""


def export(
    news_dir: str | Path,
    web_dir: str | Path,
    out_dir: str | Path,
) -> int:
    """Write the static site. Returns the number of days exported."""
    news = Path(news_dir)
    web = Path(web_dir)
    out = Path(out_dir)

    _prepare(out)

    days = digest.list_days(news)
    data = out / "data"
    (data / "day").mkdir(parents=True, exist_ok=True)

    index = []
    corpus = []

    for day in days:
        stamp = day.date.isoformat()
        topics = digest.topics_of(day.path)

        # Deliberately no "notes" key. The live API returns one; this must not.
        atomic.write_json(data / "day" / f"{stamp}.json", {
            "date": stamp,
            "html": digest.render_html(day.path),
            "tags": day.tags,
            "sources": day.sources,
            "post_count": day.post_count,
            "transcribed_count": day.transcribed_count,
            "incomplete": day.incomplete,
        })

        index.append({
            "date": stamp,
            "tags": day.tags,
            "sources": day.sources,
            "post_count": day.post_count,
            "transcribed_count": day.transcribed_count,
            "incomplete": day.incomplete,
        })

        for topic in topics:
            corpus.append({
                "date": stamp,
                "headline": topic.headline,
                "tags": topic.tags,
                "snippet": digest.snippet(topic.body),
                # Pre-lowered and pre-joined so the browser filter is a plain
                # substring test rather than per-keystroke string building.
                "text": f"{topic.headline}\n{topic.body}".lower(),
            })

    atomic.write_json(data / "days.json", {"days": index})
    atomic.write_json(data / "tags.json", {"tags": digest.all_tags(news)})
    atomic.write_json(data / "search.json", {"topics": corpus})

    _copy_assets(web, out)
    (out / NOJEKYLL).write_text("", encoding="utf-8")

    return len(days)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the read-only site.")
    parser.add_argument("--news", default="news")
    parser.add_argument("--web", default="web")
    parser.add_argument("--out", default="site")
    args = parser.parse_args(argv)

    count = export(args.news, args.web, args.out)
    print(f"exported {count} day(s) to {args.out}/")
    return 0


# --- internals -------------------------------------------------------------


def _prepare(out: Path) -> None:
    """Empty the target, refusing anything that is not ours or already empty.

    The export replaces the directory wholesale so deleted days disappear.
    That makes a mistyped --out genuinely destructive, hence the marker check.
    """
    if out.exists():
        if any(out.iterdir()) and not (out / MARKER).exists():
            raise UnsafeTarget(
                f"{out} is not empty and has no {MARKER} marker, so it was not "
                f"created by this tool. Refusing to delete its contents."
            )
        shutil.rmtree(out)

    out.mkdir(parents=True)
    (out / MARKER).write_text(
        "Generated by export_static.py. This directory is replaced on every "
        "export; do not put anything here by hand.\n",
        encoding="utf-8",
    )


def _copy_assets(web: Path, out: Path) -> None:
    fingerprints = {}

    for name in ASSETS:
        source = web / name
        if not source.is_file():
            continue
        if name == "index.html":
            continue                        # written last, once the hashes exist
        shutil.copy2(source, out / name)
        fingerprints[name] = _fingerprint(source)

    index = web / "index.html"
    if index.is_file():
        (out / "index.html").write_text(
            _make_static(index.read_text(encoding="utf-8"), fingerprints),
            encoding="utf-8",
        )


def _make_static(html: str, fingerprints: dict[str, str]) -> str:
    """Flip the page into read-only mode, drop live-only panels, bust caches."""
    html = html.replace('data-mode="live"', 'data-mode="static"')
    html = _LIVE_ONLY.sub("", html)

    # GitHub Pages serves assets with max-age=600, so a fresh deploy is invisible
    # for up to ten minutes unless the URL changes. A content hash in the query
    # string means a changed file is always a new URL.
    for name, stamp in fingerprints.items():   # not `digest`: shadows the module
        html = html.replace(f'"{name}"', f'"{name}?v={stamp}"')

    return html


def _fingerprint(path: Path, length: int = 10) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:length]


if __name__ == "__main__":
    sys.exit(main())
